### ISSUE TITLE
Travis CI building issue

### ISSUE THREAD

**Issue by QuentinDenisot** [ESGI-Grandval-Thematique/Unsecure#6]
## Description
Travis configuration file is not adapted to run on our project currently.

## Expected Behavior
It should run by pulling the php-cs-fixer using docker.

## Actual Behavior
Currently the script section is just displaying a list.

## Possible Fix
Just changing the script section.

## Context
Travis CI can't run properly on pull requests.

## Your Environment
* Link to your project: https://github.com/ESGI-Grandval-Thematique/Unsecure

**Comment by theosenoussaoui** [comment]
This issue has been solved with the latest pull-request.
